[package]
name = "crawler_si"
version = "0.2.0"
edition = "2021"
authors = [ "Nathan Ulmer" ]

[[bin]]
name = "crawler_si"
path = "src/main.rs"

[dependencies]
crawler = { path = "../crawler", version = "0.2.0" }
